In [1]:
from langchain_community.document_loaders import TextLoader, DataFrameLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_google_genai import ChatGoogleGenerativeAI, GoogleGenerativeAIEmbeddings
from langchain_chroma import Chroma
# print("All imports successful!")

c:\Users\goyal\OneDrive\Desktop\Book-Recommendation-System\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
print("All imports Pretty  Successfuly !")

All imports Pretty  Successfuly !

In [4]:
from sentence_transformers import SentenceTransformer

# This will download the model (approx. 80MB) on the first run
model = SentenceTransformer('all-MiniLM-L6-v2')

sentences = ["This is an example query", "Each sentence is converted into a vector"]
embeddings = model.encode(sentences)

print(f"Embedding shape: {embeddings.shape}") # Should be (2, 384)

Embedding shape: (2, 384)

In [ ]:
# import os
# from dotenv import load_dotenv
# from langchain_google_genai import ChatGoogleGenerativeAI, GoogleGenerativeAIEmbeddings

# # 1. Load your API key
# load_dotenv()
# # In your setup code
# llm = ChatGoogleGenerativeAI(
#     model="gemini-3-pro-preview",    
#     google_api_key=os.getenv("GOOGLE_API_KEY"),
#     temperature=0.0
# )
# # AND CHANGE YOUR EMBEDDINGS TO:
# embeddings = GoogleGenerativeAIEmbeddings(
#     model="models/gemini-embedding-001",  # ✅ Confirmed working embedding model
#     # google_api_key=os.getenv("GOOGLE_API_KEY")                # ✅ Don't forget to pass the key here too!
# )

In [3]:
import pandas as pd 

books=pd.read_csv("books_cleaned.csv")

books["tagged_description"].to_csv("tagged_descriptions.text",
                                    sep="\n" , index=False, header=False)

In [4]:
# 1. Ensure TextLoader is imported (Fixes the NameError from before)
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter

raw_data = TextLoader("tagged_descriptions.text", encoding="utf-8").load()

# 2. Set chunk_size to 1000 (roughly the length of a book summary)
# and chunk_overlap to 100 (keeps context between chunks)
text_splitter = CharacterTextSplitter(
    chunk_size=1000, 
    chunk_overlap=100, 
    separator="\n"
)

# 3. This will now run without the ValueError
documents = text_splitter.split_documents(raw_data)

Created a chunk of size 1170, which is longer than the specified 1000
Created a chunk of size 1216, which is longer than the specified 1000
Created a chunk of size 1090, which is longer than the specified 1000
Created a chunk of size 1191, which is longer than the specified 1000
Created a chunk of size 1269, which is longer than the specified 1000
Created a chunk of size 2012, which is longer than the specified 1000
Created a chunk of size 1227, which is longer than the specified 1000
Created a chunk of size 1186, which is longer than the specified 1000
Created a chunk of size 1216, which is longer than the specified 1000
Created a chunk of size 1193, which is longer than the specified 1000
Created a chunk of size 1059, which is longer than the specified 1000
Created a chunk of size 1272, which is longer than the specified 1000
Created a chunk of size 1637, which is longer than the specified 1000
Created a chunk of size 1134, which is longer than the specified 1000
Created a chunk of size 1327, which is longer than the specified 1000
Created a chunk of size 1121, which is longer than the specified 1000
Created a chunk of size 1197, which is longer than the specified 1000
Created a chunk of size 2014, which is longer than the specified 1000
Created a chunk of size 1288, which is longer than the specified 1000
Created a chunk of size 1233, which is longer than the specified 1000
Created a chunk of size 1244, which is longer than the specified 1000
Created a chunk of size 1128, which is longer than the specified 1000
Created a chunk of size 1075, which is longer than the specified 1000
Created a chunk of size 1320, which is longer than the specified 1000
Created a chunk of size 2836, which is longer than the specified 1000
Created a chunk of size 1143, which is longer than the specified 1000

Created a chunk of size 1006, which is longer than the specified 1000
Created a chunk of size 2512, which is longer than the specified 1000
Created a chunk of size 1424, which is longer than the specified 1000
Created a chunk of size 1085, which is longer than the specified 1000
Created a chunk of size 1146, which is longer than the specified 1000
Created a chunk of size 1270, which is longer than the specified 1000
Created a chunk of size 1088, which is longer than the specified 1000
Created a chunk of size 1814, which is longer than the specified 1000
Created a chunk of size 1832, which is longer than the specified 1000
Created a chunk of size 1066, which is longer than the specified 1000
Created a chunk of size 1182, which is longer than the specified 1000
Created a chunk of size 1286, which is longer than the specified 1000
Created a chunk of size 1644, which is longer than the specified 1000
Created a chunk of size 1932, which is longer than the specified 1000
Created a chunk of size 2010, which is longer than the specified 1000
Created a chunk of size 2287, which is longer than the specified 1000
Created a chunk of size 1005, which is longer than the specified 1000
Created a chunk of size 1144, which is longer than the specified 1000
Created a chunk of size 1145, which is longer than the specified 1000
Created a chunk of size 1088, which is longer than the specified 1000
Created a chunk of size 1485, which is longer than the specified 1000
Created a chunk of size 1137, which is longer than the specified 1000
Created a chunk of size 1034, which is longer than the specified 1000
Created a chunk of size 1017, which is longer than the specified 1000
Created a chunk of size 1090, which is longer than the specified 1000
Created a chunk of size 1914, which is longer than the specified 1000
Created a chunk of size 2618, which is longer than the specified 1000
Created a chunk of size 1582, which is longer than the specified 1000
Created a chunk of size 1532, which is longer than the specified 1000
Created a chunk of size 2032, which is longer than the specified 1000
Created a chunk of size 1621, which is longer than the specified 1000
Created a chunk of size 1191, which is longer than the specified 1000
Created a chunk of size 1284, which is longer than the specified 1000
Created a chunk of size 1270, which is longer than the specified 1000
Created a chunk of size 1279, which is longer than the specified 1000
Created a chunk of size 1058, which is longer than the specified 1000
Created a chunk of size 1165, which is longer than the specified 1000
Created a chunk of size 1060, which is longer than the specified 1000
Created a chunk of size 1086, which is longer than the specified 1000
Created a chunk of size 2764, which is longer than the specified 1000
Created a chunk of size 1035, which is longer than the specified 1000
Created a chunk of size 1012, which is longer than the specified 1000
Created a chunk of size 1066, which is longer than the specified 1000
Created a chunk of size 1226, which is longer than the specified 1000
Created a chunk of size 1807, which is longer than the specified 1000
Created a chunk of size 1019, which is longer than the specified 1000
Created a chunk of size 1270, which is longer than the specified 1000
Created a chunk of size 1773, which is longer than the specified 1000
Created a chunk of size 1272, which is longer than the specified 1000
Created a chunk of size 1021, which is longer than the specified 1000
Created a chunk of size 1179, which is longer than the specified 1000
Created a chunk of size 1717, which is longer than the specified 1000
Created a chunk of size 1683, which is longer than the specified 1000
Created a chunk of size 1130, which is longer than the specified 1000
Created a chunk of size 2007, which is longer than the specified 1000
Created a chunk of size 1173, which is longer than the specified 1000
Created a chunk of size 2143, which is longer than the specified 1000
Created a chunk of size 1324, which is longer than the specified 1000
Created a chunk of size 1114, which is longer than the specified 1000
Created a chunk of size 1318, which is longer than the specified 1000
Created a chunk of size 1123, which is longer than the specified 1000
Created a chunk of size 1020, which is longer than the specified 1000
Created a chunk of size 1009, which is longer than the specified 1000
Created a chunk of size 1059, which is longer than the specified 1000
Created a chunk of size 1257, which is longer than the specified 1000
Created a chunk of size 1100, which is longer than the specified 1000
Created a chunk of size 1145, which is longer than the specified 1000
Created a chunk of size 1552, which is longer than the specified 1000
Created a chunk of size 1654, which is longer than the specified 1000
Created a chunk of size 1497, which is longer than the specified 1000
Created a chunk of size 1279, which is longer than the specified 1000
Created a chunk of size 1048, which is longer than the specified 1000
Created a chunk of size 1668, which is longer than the specified 1000
Created a chunk of size 1618, which is longer than the specified 1000
Created a chunk of size 1097, which is longer than the specified 1000
Created a chunk of size 1599, which is longer than the specified 1000
Created a chunk of size 1962, which is longer than the specified 1000
Created a chunk of size 1710, which is longer than the specified 1000
Created a chunk of size 1949, which is longer than the specified 1000
Created a chunk of size 1029, which is longer than the specified 1000
Created a chunk of size 1809, which is longer than the specified 1000
Created a chunk of size 1520, which is longer than the specified 1000
Created a chunk of size 1089, which is longer than the specified 1000
Created a chunk of size 1095, which is longer than the specified 1000
Created a chunk of size 1169, which is longer than the specified 1000
Created a chunk of size 1261, which is longer than the specified 1000
Created a chunk of size 1482, which is longer than the specified 1000
Created a chunk of size 1039, which is longer than the specified 1000
Created a chunk of size 1087, which is longer than the specified 1000
Created a chunk of size 1445, which is longer than the specified 1000
Created a chunk of size 1268, which is longer than the specified 1000
Created a chunk of size 1146, which is longer than the specified 1000
Created a chunk of size 1371, which is longer than the specified 1000
Created a chunk of size 1624, which is longer than the specified 1000
Created a chunk of size 1167, which is longer than the specified 1000
Created a chunk of size 1178, which is longer than the specified 1000
Created a chunk of size 1181, which is longer than the specified 1000
Created a chunk of size 1011, which is longer than the specified 1000
Created a chunk of size 1024, which is longer than the specified 1000
Created a chunk of size 1359, which is longer than the specified 1000
Created a chunk of size 1174, which is longer than the specified 1000
Created a chunk of size 1396, which is longer than the specified 1000
Created a chunk of size 1218, which is longer than the specified 1000
Created a chunk of size 2211, which is longer than the specified 1000
Created a chunk of size 1373, which is longer than the specified 1000
Created a chunk of size 2879, which is longer than the specified 1000
Created a chunk of size 1281, which is longer than the specified 1000
Created a chunk of size 1716, which is longer than the specified 1000
Created a chunk of size 1640, which is longer than the specified 1000
Created a chunk of size 2400, which is longer than the specified 1000
Created a chunk of size 2122, which is longer than the specified 1000
Created a chunk of size 1490, which is longer than the specified 1000
Created a chunk of size 1693, which is longer than the specified 1000
Created a chunk of size 1420, which is longer than the specified 1000
Created a chunk of size 1175, which is longer than the specified 1000
Created a chunk of size 1361, which is longer than the specified 1000
Created a chunk of size 2183, which is longer than the specified 1000
Created a chunk of size 1095, which is longer than the specified 1000
Created a chunk of size 2173, which is longer than the specified 1000
Created a chunk of size 1456, which is longer than the specified 1000
Created a chunk of size 1456, which is longer than the specified 1000
Created a chunk of size 1975, which is longer than the specified 1000
Created a chunk of size 1989, which is longer than the specified 1000
Created a chunk of size 1650, which is longer than the specified 1000
Created a chunk of size 2725, which is longer than the specified 1000
Created a chunk of size 1634, which is longer than the specified 1000
Created a chunk of size 1286, which is longer than the specified 1000
Created a chunk of size 1486, which is longer than the specified 1000
Created a chunk of size 1051, which is longer than the specified 1000
Created a chunk of size 1005, which is longer than the specified 1000
Created a chunk of size 1152, which is longer than the specified 1000
Created a chunk of size 1218, which is longer than the specified 1000
Created a chunk of size 1034, which is longer than the specified 1000
Created a chunk of size 2458, which is longer than the specified 1000
Created a chunk of size 1351, which is longer than the specified 1000
Created a chunk of size 1273, which is longer than the specified 1000
Created a chunk of size 1119, which is longer than the specified 1000
Created a chunk of size 1550, which is longer than the specified 1000
Created a chunk of size 1203, which is longer than the specified 1000
Created a chunk of size 1162, which is longer than the specified 1000
Created a chunk of size 1151, which is longer than the specified 1000
Created a chunk of size 1026, which is longer than the specified 1000
Created a chunk of size 1776, which is longer than the specified 1000
Created a chunk of size 1167, which is longer than the specified 1000
Created a chunk of size 1011, which is longer than the specified 1000
Created a chunk of size 1019, which is longer than the specified 1000
Created a chunk of size 1325, which is longer than the specified 1000
Created a chunk of size 1215, which is longer than the specified 1000
Created a chunk of size 1125, which is longer than the specified 1000
Created a chunk of size 1600, which is longer than the specified 1000
Created a chunk of size 1965, which is longer than the specified 1000
Created a chunk of size 2452, which is longer than the specified 1000
Created a chunk of size 1798, which is longer than the specified 1000
Created a chunk of size 1570, which is longer than the specified 1000
Created a chunk of size 1221, which is longer than the specified 1000
Created a chunk of size 1382, which is longer than the specified 1000
Created a chunk of size 1454, which is longer than the specified 1000
Created a chunk of size 1104, which is longer than the specified 1000
Created a chunk of size 1300, which is longer than the specified 1000
Created a chunk of size 1763, which is longer than the specified 1000
Created a chunk of size 1006, which is longer than the specified 1000
Created a chunk of size 1024, which is longer than the specified 1000
Created a chunk of size 1066, which is longer than the specified 1000
Created a chunk of size 1011, which is longer than the specified 1000
Created a chunk of size 1066, which is longer than the specified 1000
Created a chunk of size 1631, which is longer than the specified 1000
Created a chunk of size 1595, which is longer than the specified 1000
Created a chunk of size 1589, which is longer than the specified 1000
Created a chunk of size 1261, which is longer than the specified 1000
Created a chunk of size 1130, which is longer than the specified 1000
Created a chunk of size 1107, which is longer than the specified 1000
Created a chunk of size 1082, which is longer than the specified 1000
Created a chunk of size 1535, which is longer than the specified 1000
Created a chunk of size 1204, which is longer than the specified 1000
Created a chunk of size 1095, which is longer than the specified 1000
Created a chunk of size 1249, which is longer than the specified 1000
Created a chunk of size 1058, which is longer than the specified 1000
Created a chunk of size 1213, which is longer than the specified 1000
Created a chunk of size 1013, which is longer than the specified 1000
Created a chunk of size 1354, which is longer than the specified 1000
Created a chunk of size 1414, which is longer than the specified 1000
Created a chunk of size 1025, which is longer than the specified 1000
Created a chunk of size 1218, which is longer than the specified 1000
Created a chunk of size 1133, which is longer than the specified 1000
Created a chunk of size 1199, which is longer than the specified 1000
Created a chunk of size 1893, which is longer than the specified 1000
Created a chunk of size 3170, which is longer than the specified 1000
Created a chunk of size 1534, which is longer than the specified 1000
Created a chunk of size 1590, which is longer than the specified 1000
Created a chunk of size 1611, which is longer than the specified 1000
Created a chunk of size 1625, which is longer than the specified 1000
Created a chunk of size 1421, which is longer than the specified 1000
Created a chunk of size 1116, which is longer than the specified 1000
Created a chunk of size 1130, which is longer than the specified 1000
Created a chunk of size 1038, which is longer than the specified 1000
Created a chunk of size 1141, which is longer than the specified 1000
Created a chunk of size 1180, which is longer than the specified 1000
Created a chunk of size 1050, which is longer than the specified 1000
Created a chunk of size 1002, which is longer than the specified 1000
Created a chunk of size 1213, which is longer than the specified 1000
Created a chunk of size 1171, which is longer than the specified 1000
Created a chunk of size 2036, which is longer than the specified 1000
Created a chunk of size 1117, which is longer than the specified 1000
Created a chunk of size 1438, which is longer than the specified 1000
Created a chunk of size 1115, which is longer than the specified 1000
Created a chunk of size 1064, which is longer than the specified 1000
Created a chunk of size 1473, which is longer than the specified 1000
Created a chunk of size 1438, which is longer than the specified 1000
Created a chunk of size 1332, which is longer than the specified 1000
Created a chunk of size 1723, which is longer than the specified 1000
Created a chunk of size 1532, which is longer than the specified 1000
Created a chunk of size 1653, which is longer than the specified 1000
Created a chunk of size 1581, which is longer than the specified 1000
Created a chunk of size 1648, which is longer than the specified 1000
Created a chunk of size 1689, which is longer than the specified 1000
Created a chunk of size 2033, which is longer than the specified 1000
Created a chunk of size 1109, which is longer than the specified 1000
Created a chunk of size 1051, which is longer than the specified 1000
Created a chunk of size 1120, which is longer than the specified 1000
Created a chunk of size 1091, which is longer than the specified 1000
Created a chunk of size 1105, which is longer than the specified 1000
Created a chunk of size 1132, which is longer than the specified 1000
Created a chunk of size 1340, which is longer than the specified 1000
Created a chunk of size 1082, which is longer than the specified 1000
Created a chunk of size 1165, which is longer than the specified 1000
Created a chunk of size 1005, which is longer than the specified 1000
Created a chunk of size 1087, which is longer than the specified 1000
Created a chunk of size 1005, which is longer than the specified 1000
Created a chunk of size 1228, which is longer than the specified 1000
Created a chunk of size 1237, which is longer than the specified 1000
Created a chunk of size 2942, which is longer than the specified 1000
Created a chunk of size 1120, which is longer than the specified 1000
Created a chunk of size 1492, which is longer than the specified 1000
Created a chunk of size 1159, which is longer than the specified 1000
Created a chunk of size 1210, which is longer than the specified 1000
Created a chunk of size 1491, which is longer than the specified 1000
Created a chunk of size 1088, which is longer than the specified 1000
Created a chunk of size 1804, which is longer than the specified 1000
Created a chunk of size 1597, which is longer than the specified 1000
Created a chunk of size 1032, which is longer than the specified 1000
Created a chunk of size 1363, which is longer than the specified 1000
Created a chunk of size 1645, which is longer than the specified 1000
Created a chunk of size 1384, which is longer than the specified 1000
Created a chunk of size 1765, which is longer than the specified 1000
Created a chunk of size 1973, which is longer than the specified 1000
Created a chunk of size 1242, which is longer than the specified 1000
Created a chunk of size 1121, which is longer than the specified 1000
Created a chunk of size 1053, which is longer than the specified 1000
Created a chunk of size 1008, which is longer than the specified 1000
Created a chunk of size 1121, which is longer than the specified 1000
Created a chunk of size 1129, which is longer than the specified 1000
Created a chunk of size 1039, which is longer than the specified 1000
Created a chunk of size 1282, which is longer than the specified 1000
Created a chunk of size 1477, which is longer than the specified 1000
Created a chunk of size 1270, which is longer than the specified 1000
Created a chunk of size 1221, which is longer than the specified 1000
Created a chunk of size 1005, which is longer than the specified 1000
Created a chunk of size 1047, which is longer than the specified 1000
Created a chunk of size 1054, which is longer than the specified 1000
Created a chunk of size 1019, which is longer than the specified 1000
Created a chunk of size 1179, which is longer than the specified 1000
Created a chunk of size 1248, which is longer than the specified 1000
Created a chunk of size 1051, which is longer than the specified 1000
Created a chunk of size 1127, which is longer than the specified 1000
Created a chunk of size 1129, which is longer than the specified 1000
Created a chunk of size 1027, which is longer than the specified 1000
Created a chunk of size 1292, which is longer than the specified 1000
Created a chunk of size 1093, which is longer than the specified 1000
Created a chunk of size 1566, which is longer than the specified 1000
Created a chunk of size 1151, which is longer than the specified 1000
Created a chunk of size 1216, which is longer than the specified 1000
Created a chunk of size 1217, which is longer than the specified 1000
Created a chunk of size 1068, which is longer than the specified 1000
Created a chunk of size 1083, which is longer than the specified 1000
Created a chunk of size 1044, which is longer than the specified 1000
Created a chunk of size 1257, which is longer than the specified 1000
Created a chunk of size 1175, which is longer than the specified 1000
Created a chunk of size 1077, which is longer than the specified 1000
Created a chunk of size 1265, which is longer than the specified 1000
Created a chunk of size 1622, which is longer than the specified 1000
Created a chunk of size 1063, which is longer than the specified 1000
Created a chunk of size 1581, which is longer than the specified 1000
Created a chunk of size 1043, which is longer than the specified 1000
Created a chunk of size 1047, which is longer than the specified 1000
Created a chunk of size 1452, which is longer than the specified 1000

In [14]:
import os
import shutil
import time
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings

# 1. SETUP MODEL (This is your all-MiniLM-L6-v2)
model_name = "sentence-transformers/all-MiniLM-L6-v2"
hf_embeddings = HuggingFaceEmbeddings(model_name=model_name, model_kwargs={'device': 'cpu'})

# 2. PATH SETUP
db_path = "./book_db_final_version" 
if os.path.exists(db_path):
    shutil.rmtree(db_path)

# 3. INITIAL BATCH (Creates the database)
print("🚀 Starting ingestion...")
batch_size = 40
db_books = Chroma.from_documents(
    documents=documents[:batch_size], 
    embedding=hf_embeddings, 
    persist_directory=db_path
)
print(f"✅ Initial {batch_size} books stored.")

# 4. LOOP FOR REMAINING BOOKS
for i in range(batch_size, len(documents), batch_size):
    batch = documents[i : i + batch_size]
    db_books.add_documents(batch)
    print(f"✅ Progress: {i + len(batch)} / {len(documents)} books stored.")
    time.sleep(5) # Small pause to let the CPU breathe

print("\n✨ ALL BOOKS STORED SUCCESSFULLY!")

🚀 Starting ingestion...
✅ Initial 40 books stored.
✅ Progress: 80 / 2941 books stored.
✅ Progress: 120 / 2941 books stored.
✅ Progress: 160 / 2941 books stored.
✅ Progress: 200 / 2941 books stored.
✅ Progress: 240 / 2941 books stored.
✅ Progress: 280 / 2941 books stored.
✅ Progress: 320 / 2941 books stored.
✅ Progress: 360 / 2941 books stored.
✅ Progress: 400 / 2941 books stored.
✅ Progress: 440 / 2941 books stored.
✅ Progress: 480 / 2941 books stored.
✅ Progress: 520 / 2941 books stored.
✅ Progress: 560 / 2941 books stored.
✅ Progress: 600 / 2941 books stored.
✅ Progress: 640 / 2941 books stored.
✅ Progress: 680 / 2941 books stored.
✅ Progress: 720 / 2941 books stored.
✅ Progress: 760 / 2941 books stored.
✅ Progress: 800 / 2941 books stored.
✅ Progress: 840 / 2941 books stored.
✅ Progress: 880 / 2941 books stored.
✅ Progress: 920 / 2941 books stored.
✅ Progress: 960 / 2941 books stored.
✅ Progress: 1000 / 2941 books stored.
✅ Progress: 1040 / 2941 books stored.
✅ Progress: 1080 / 2941 books stored.
✅ Progress: 1120 / 2941 books stored.
✅ Progress: 1160 / 2941 books stored.
✅ Progress: 1200 / 2941 books stored.
✅ Progress: 1240 / 2941 books stored.
✅ Progress: 1280 / 2941 books stored.
✅ Progress: 1320 / 2941 books stored.
✅ Progress: 1360 / 2941 books stored.
✅ Progress: 1400 / 2941 books stored.
✅ Progress: 1440 / 2941 books stored.
✅ Progress: 1480 / 2941 books stored.
✅ Progress: 1520 / 2941 books stored.
✅ Progress: 1560 / 2941 books stored.
✅ Progress: 1600 / 2941 books stored.
✅ Progress: 1640 / 2941 books stored.
✅ Progress: 1680 / 2941 books stored.
✅ Progress: 1720 / 2941 books stored.
✅ Progress: 1760 / 2941 books stored.
✅ Progress: 1800 / 2941 books stored.
✅ Progress: 1840 / 2941 books stored.
✅ Progress: 1880 / 2941 books stored.
✅ Progress: 1920 / 2941 books stored.
✅ Progress: 1960 / 2941 books stored.
✅ Progress: 2000 / 2941 books stored.
✅ Progress: 2040 / 2941 books stored.
✅ Progress: 2080 / 2941 books stored.
✅ Progress: 2120 / 2941 books stored.
✅ Progress: 2160 / 2941 books stored.
✅ Progress: 2200 / 2941 books stored.
✅ Progress: 2240 / 2941 books stored.
✅ Progress: 2280 / 2941 books stored.
✅ Progress: 2320 / 2941 books stored.
✅ Progress: 2360 / 2941 books stored.
✅ Progress: 2400 / 2941 books stored.
✅ Progress: 2440 / 2941 books stored.
✅ Progress: 2480 / 2941 books stored.
✅ Progress: 2520 / 2941 books stored.
✅ Progress: 2560 / 2941 books stored.
✅ Progress: 2600 / 2941 books stored.
✅ Progress: 2640 / 2941 books stored.
✅ Progress: 2680 / 2941 books stored.
✅ Progress: 2720 / 2941 books stored.
✅ Progress: 2760 / 2941 books stored.
✅ Progress: 2800 / 2941 books stored.
✅ Progress: 2840 / 2941 books stored.
✅ Progress: 2880 / 2941 books stored.
✅ Progress: 2920 / 2941 books stored.
✅ Progress: 2941 / 2941 books stored.

✨ ALL BOOKS STORED SUCCESSFULLY!

In [5]:
import os
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings

# 1. Re-initialize the exact same model wrapper used for building
model_name = "sentence-transformers/all-MiniLM-L6-v2"
hf_embeddings = HuggingFaceEmbeddings(model_name=model_name)

# 2. Path to your saved folder
db_path = "./book_db_final_version"

if os.path.exists(db_path):
    # This LOADS the database from disk
    db_books = Chroma(
        persist_directory=db_path,
        embedding_function=hf_embeddings  # Must use the wrapper here!
    )
    
    # Verify the count
    num_books = len(db_books.get()['ids'])
    print(f"✅ Database loaded successfully with {num_books} books.")
else:
    print(f"❌ Error: Folder '{db_path}' not found. Run the ingestion code first!")

✅ Database loaded successfully with 2941 books.

In [7]:
query = "A book about Roman history"
results = db_books.similarity_search(query, k=10)
print("results: ", results)

results:  [Document(id='9a4510f6-2840-4557-8c5c-b2781ef5827c', metadata={'source': 'tagged_descriptions.text'}, page_content="9780380710829 | The lives of ancient Rome's men--general Gaius Marius and his rival Lucius Cornelius Sulla--unfold amid Republican Rome's struggle in a world of treachery and barbarism\n9780380710843 | The fourth novel of the Masters of Rome series focuses on the women in the life of the Roman emperor Gaius Julius Caesar at the height of his power"), Document(id='04ba75a6-5cb9-4870-9ed7-300c27a4cfc8', metadata={'source': 'tagged_descriptions.text'}, page_content="9780192833006 | Cornelius Tacitus, Rome's greatest historian, was inspired to take up his pen when the assassination of Domitian ended `fifteen years of enforced silence'. Agricola is the biography of his late father-in-law and an account of Roman Britain. Germania gives insight into Rome's most dangerous enemies, the Germans, and is the only surviving specimen from the ancient world of an ethnographic study. Each in its way has had immense influence on our perception of Rome and the northern `barbarians' and the edition reflects recent research in Roman-British and Roman-German history. - ;`Long may the barbarians continue, I pray, if not to love us, at least to hate one another.' Cornelius Tacitus, Rome's greatest historian and the last great writer of classical Latin prose, produced his first two books in AD 98. He was inspired to take up his pen when the assassination of Domitian ended `fifteen years of enforced silence'. The first products were brief: the biography of his late father-in-law Julius Agricola and an account of Rome's most dangerous enemies, the Germans. Since Agricola's claim to fame was that as governor for seven years he had completed the conquest of Britain, begun four decades earlier, much of the first work is devoted to Britain and its people. The second is the only surviving specimen from the ancient world of an ethnographic study. Each in its way has had immense influence on our perception of Rome and the northern `barbarians'. This edition reflects recent research in Roman-British and Roman-German history and includes newly discovered evidence on Tacitus' early career. -"), Document(id='3f8c09b1-9fdd-4744-bffa-68d6a9b36b62', metadata={'source': 'tagged_descriptions.text'}, page_content='"9780671024208 | Now in paperback--the sweeping epic of ancient Rome from the #1 bestselling author of ""The Thorn Birds"" that brings to life Gaius Julius Caesar during the last days of the Roman Republic."\n9780671024239 | Plagued by vivid nightmares of the summer house he had shared with his late wife, grieving widower Mike Noonan returns to his former Maine getaway, only to find a town in the grip of a ruthless millionaire and tormented by a series of ghostly visitations. Reprint.\n9780671024819 | When a quiet college town is invaded by bloodhungry demons, a savvy college freshman teams up with a local amateur historian to uncover a terrifying crime in the town\'s past. Reprint.'), Document(id='0f1a95eb-856a-40c7-af0c-adf2e5924b99', metadata={'source': 'tagged_descriptions.text'}, page_content='9781565849426 | Parenti presents a story of popular resistance against entrenched power and wealth. As he carefully weighs the evidence in the murder of Caesar, he sketches in the background to the crime with fascinating detail about Roman society.'), Document(id='a54f403a-cf9e-493a-934e-22427827510c', metadata={'source': 'tagged_descriptions.text'}, page_content="9780760768952 | Among the most durable and engaging texts in world literature, Julius Caesar's Conquest of Gaul tells how he and his legions conquered much of modern France in less than a decade (58-51 BCE), despite determined resistance. Perhaps the most famous Roman ever, Gaius Julius Caesar created a legacy which has resonated, for good or ill, throughout Western culture. Architect of an imperial system, eponymous sponsor of a reformed calendar system, orator second only to Cicero, conqueror of Gaul: Surely those accomplishments in the diverse fields of politics, applied mathematics, rhetoric, and military science would justify his eminence. Nevertheless, the high literary quality and historical value of this seemingly modest account match its exciting story of diplomatic maneuverings, shifting alliances, and military actions; the final chapters culminate in the revolt of the united Gallic tribes under Vercingetorix, France's first national hero, and are as compelling as any contemporary spy thriller."), Document(id='6bb1cf3b-d9c6-49dd-9b23-11b121838184', metadata={'source': 'tagged_descriptions.text'}, page_content="9780688090258 | In the last volume of the parable of Earth's destruction and humanity's doomed flight from it, Mariane O'Hara frantically records the lives of her family and contemporaries when most of the earth's history and literature is wiped out from computer banks.\n9780688093686 | A story tracing the creation of Republican Rome presents those who founded an empire, including Marius and Sulla, each determined to become the First Man of Rome"), Document(id='9155ab0c-0b11-405d-91fb-b5e40c999d8e', metadata={'source': 'tagged_descriptions.text'}, page_content='9780674990333 | Cicero (Marcus Tullius, 106–43 BCE), Roman lawyer, orator, politician and philosopher, of whom we know more than of any other Roman, lived through the stirring era which saw the rise, dictatorship, and death of Julius Caesar in a tottering republic. In his political speeches especially and in his correspondence we see the excitement, tension and intrigue of politics and the part he played in the turmoil of the time. Of about 106 speeches, delivered before the Roman people or the Senate if they were political, before jurors if judicial, 58 survive (a few of them incompletely). In the fourteenth century Petrarch and other Italian humanists discovered manuscripts containing more than 900 letters of which more than 800 were written by Cicero and nearly 100 by others to him. These afford a revelation of the man all the more striking because most were not written for publication. Six rhetorical works survive and another in fragments. Philosophical works include seven extant major compositions and a number of others; and some lost. There is also poetry, some original, some as translations from the Greek. The Loeb Classical Library edition of Cicero is in twenty-nine volumes.'), Document(id='9161bc71-375c-48bd-ae8e-9826be3e6f83', metadata={'source': 'tagged_descriptions.text'}, page_content="9780312320195 | Like so many young men in later generations, Roman playboy/detective Decius Caecilius Metellus the Younger is faced with the necessity of serving in his country's armed forces. Since a dangerous enemy has become powerful in the politics of Rome, Decius is just as well out of the city for a while. He sets out to join Caesar in Gaul (where the general has come and seen, but has as yet not been able to conquer. The occupying Roman army is at a standstill. When Decius shows up in full parade regalia (much to the amusement of the more informally uniformed veterans) and accompanied only by his young personal slave. Caesar sets him the task of discovering who murdered one of his centurions, a cruel and unfair officer feared and hated by every man of the one hundred soldiers under him. A further prod to Decius is that the main suspect is a youth whose father is a close friend of the Metellus family. With Caesar's decree that another killer be found in a matter of hours or the young man dies, Decius has his work cut out for him. John Maddox Roberts's series set in the first century A.D. vividly brings to readers a strong sense of the everyday life of the ancient Romans in the context of our own."), Document(id='5f9783cd-1ba8-480f-b9b9-f5475a4a3b33', metadata={'source': 'tagged_descriptions.text'}, page_content="9780521348355 | De Officiis (On Duties) is Cicero's last theoretical work and contains his analysis, in a Greek theoretical framework, of the political and ethical values of the Roman governing class in the late Republic. It has often been treated merely as a key to the Greek philosophical works that Cicero used, but this volume aims to render De Officiis, which had a profound impact upon subsequent political thinkers, more intelligible by explaining its relation to its own time and place. All the standard series features are present, including a wholly new translation, a concise introduction by a leading scholar, select bibliography, chronology, notes on vocabulary and brief biographies of the most prominent individuals mentioned in the text."), Document(id='22fd8627-4712-4b8f-a4aa-bd3dbb59a4f4', metadata={'source': 'tagged_descriptions.text'}, page_content='"9780674995741 | One of antiquity\'s greatest poets, Euripides (ca. 485-406 BCE) has been prized in every age for the pathos, terror, surprising plot twists, and intellectual probing of his dramatic creations. Here, in the third volume of a new edition that is receiving much praise, is the text and translation of three of his plays. Trojan Women, a play about the causes and consequences of war, develops the theme of the tragic unpredictability of life. Iphigenia among the Taurians and Ion exhibit tragic themes and situations (the murder of close relatives). Each ends happily with a joyful reunion. As in the first three volumes of this edition, David Kovacs gives us a freshly edited Greek text and an admired new translation that, in the words of Greece and Rome, is ""close to the Greek and reads fluently and well;"" his introduction to each play and explanatory notes offer readers judicious guidance."')]

In [8]:
# .replace('"', '') removes any double quotes found in that first segment
isbn_str = results[0].page_content.split(" ")[0].replace('"', '').strip()
books[books["isbn13"] == int(isbn_str)]
# print(results[0].metadata)

,isbn13,isbn10,title,authors,categories,thumbnail,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
1753,9780380710829,038071082X,The Grass Crown,Colleen McCullough,Fiction,http://books.google.com/books/content?id=Kt3gN...,1992.0,4.29,1104.0,9397.0,The Grass Crown,9780380710829 | The lives of ancient Rome's me...

In [17]:
def retrieve_symmentaic_recommendations(
        query: str,
        top_k: int = 10
    ,
)-> pd.DataFrame:
    recs=db_books.similarity_search(query, k=top_k)
    book_list=[]
    for i in range(len(recs)):
        isbn_str = recs[i].page_content.split(" ")[0].replace('"', '').strip()
        book_info=books[books["isbn13"] == int(isbn_str)]
        book_list.append(book_info)
#    return pd.concat(book_list).reset_index(drop=True)
    return pd.concat(book_list).reset_index(drop=True)

In [18]:
results_df=retrieve_symmentaic_recommendations("A book about a past",top_k=10)
results_df

,isbn13,isbn10,title,authors,categories,thumbnail,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780061159176,0061159174,The Known World,Edward P. Jones,Fiction,http://books.google.com/books/content?id=NE-vs...,2006.0,3.83,388.0,28962.0,The Known World,9780061159176 | One of the most acclaimed nove...
1,9780300094008,0300094000,Marcel Proust,William C. Carter,Biography & Autobiography,http://books.google.com/books/content?id=NxTaY...,2002.0,4.32,992.0,13.0,Marcel Proust: A Life,9780300094008 | This book is a magisterial acc...
2,9780618057078,0618057072,The Origin of Consciousness in the Breakdown o...,Julian Jaynes,Philosophy,http://books.google.com/books/content?id=6Q0kS...,2000.0,4.24,491.0,3258.0,The Origin of Consciousness in the Breakdown o...,"9780618057078 | At the heart of this classic, ..."
3,9781564780614,1564780619,Letters,John Barth,Fiction,http://books.google.com/books/content?id=m0MZc...,1994.0,3.82,772.0,202.0,Letters: A Novel,"9781564780614 | Basically, [Barth] takes sever..."
4,9780393328622,0393328627,The History of Love: A Novel,Nicole Krauss,Fiction,http://books.google.com/books/content?id=-Il7X...,2006.0,3.92,255.0,107024.0,The History of Love: A Novel,9780393328622 | Sixty years after a book's pub...
5,9781593083779,1593083777,Swann's Way,Marcel Proust;Elizabeth Dalton,Fiction,http://books.google.com/books/content?id=wHUIr...,2005.0,4.14,466.0,18.0,Swann's Way,9781593083779 | Presents the first book of Pro...
6,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 | This book tells the tale of a ...
7,9780811215923,081121592X,Borges and the Eternal Orangutans,Luís Fernando Veríssimo;Margaret Jull Costa,Fiction,http://books.google.com/books/content?id=G5cn9...,2005.0,3.79,135.0,538.0,Borges and the Eternal Orangutans,9780811215923 | Vogelstein is a loner who has ...
8,9781565849655,1565849655,Interesting Times,Eric J. Hobsbawm,Biography & Autobiography,http://books.google.com/books/content?id=EgEMv...,2005.0,4.06,448.0,359.0,Interesting Times: A Twentieth-century Life,9781565849655 | Eric Hobsbawm has been widely ...
9,9780060593247,0060593245,Every Book Its Reader,Nicholas A. Basbanes,Literary Criticism,http://books.google.com/books/content?id=o4K_K...,2006.0,3.96,400.0,300.0,Every Book Its Reader: The Power of the Printe...,9780060593247 | Inspired by a landmark exhibit...

In [19]:
books['categories'].value_counts().reset_index().query('count>50')

                   categories  count
0                     Fiction   2111
1            Juvenile Fiction    390
2   Biography & Autobiography    311
3                     History    207
4          Literary Criticism    124
5                  Philosophy    117
6                    Religion    117
7     Comics & Graphic Novels    116
8                       Drama     86
9         Juvenile Nonfiction     57
10                    Science     56
11                     Poetry     51

In [9]:
# Updated mapping to ensure perfect string matching with the model
category_mapping = {
    'Fiction': "Fiction",
    'Juvenile Fiction': "Fiction",
    'Comics & Graphic Novels': "Fiction",
    'Drama': "Fiction",
    'Poetry': "Fiction",
    'Biography & Autobiography': "NonFiction",
    'History': "NonFiction",
    'Literary Criticism': "NonFiction",
    'Philosophy': "NonFiction",
    'Religion': "NonFiction",
    'Science': "NonFiction",
    'Juvenile Nonfiction': "NonFiction"
}

# Apply the mapping
books['broad_category'] = books['categories'].map(category_mapping)

In [10]:
books[~(books['broad_category'].isna())]
# books['broad_category'].value_counts().reset_index().query('count>50')

,isbn13,isbn10,title,authors,categories,thumbnail,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,broad_category
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 | A NOVEL THAT READERS and criti...,Fiction
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 | A memorable, mesmerizing heroi...",Fiction
8,9780006482079,0006482074,Warhost of Vastmark,Janny Wurts,Fiction,http://books.google.com/books/content?id=uOL0f...,1995.0,4.03,522.0,2966.0,Warhost of Vastmark,9780006482079 | Tricked once more by his wily ...,Fiction
30,9780006646006,000664600X,Ocean Star Express,Mark Haddon;Peter Sutton,Juvenile Fiction,http://books.google.com/books/content?id=I2QZA...,2002.0,3.50,32.0,1.0,Ocean Star Express,9780006646006 | Joe and his parents are enjoyi...,Fiction
46,9780007121014,0007121016,Taken at the Flood,Agatha Christie,Fiction,http://books.google.com/books/content?id=3gWlx...,2002.0,3.71,352.0,8852.0,Taken at the Flood,9780007121014 | A Few Weeks After Marrying An ...,Fiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5178,9781933648279,1933648279,Night Has a Thousand Eyes,Cornell Woolrich,Fiction,http://books.google.com/books/content?id=3Gk6s...,2007.0,3.77,344.0,680.0,Night Has a Thousand Eyes,"9781933648279 | ""Cornell Woolrich's novels def...",Fiction
5188,9784770028969,4770028962,Coin Locker Babies,村上龍,Fiction,http://books.google.com/books/content?id=87DJw...,2002.0,3.75,393.0,5560.0,Coin Locker Babies,9784770028969 | Rescued from the lockers in wh...,Fiction
5189,9788122200850,8122200850,"Cry, the Peacock",Anita Desai,Fiction,http://books.google.com/books/content?id=_QKwV...,1980.0,3.22,218.0,134.0,"Cry, the Peacock",9788122200850 | This book is the story of a yo...,Fiction
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 | This collection of the timeles...,NonFiction
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 | Since the three volume edition...,NonFiction

In [11]:
from transformers import pipeline,AutoConfig

# Initialize the lightweight classifier
# model="valhalla/distilbart-mnli-12-3" is the faster version
config = AutoConfig.from_pretrained("valhalla/distilbart-mnli-12-3")
config.tie_word_embeddings = False
fiction_categories = ["Fiction", "NonFiction"]
classifier = pipeline(
    "zero-shot-classification", 
    model="valhalla/distilbart-mnli-12-3",
    device=-1  # This forces the model to run on your CPU
)

Device set to use cpu

In [12]:
sequence= books.loc[books['broad_category'] == "Fiction", "tagged_description"].reset_index(drop=True)[0]

In [13]:
# # from os import pipe
# result=classifier(sequence,fiction_categories)
clean_sequence = sequence.split('|')[-1].strip()

# # 3. Classify the cleaned text
result = classifier(clean_sequence, fiction_categories)

print(f"Label: {result['labels'][0]} with score: {result['scores'][0]:.4f}")

Label: Fiction with score: 0.7222

In [14]:
import numpy as np
max_index=np.argmax(classifier(sequence,fiction_categories)['scores'])
my_label=classifier(sequence,fiction_categories)['labels'][max_index]
my_label

'Fiction'

In [15]:
def generate_predictions(sequence, function_categories):
    prediction = classifier(sequence, function_categories)
    max_index = np.argmax(prediction['scores'])
    max_label = prediction['labels'][max_index]
    return max_label

# def generate_predictions(sequence, categories):
#     # 1. Clean the sequence INSIDE the function
#     # This handles the ISBN/Pipe removal automatically
#     clean_sequence = sequence.split('|')[-1].strip()
    
#     # 2. Run the classifier with a template for better context
#     prediction = classifier(
#         clean_sequence, 
#         categories, 
#         hypothesis_template="This book is {}."
#     )
    
#     # 3. Get the top label
#     max_index = np.argmax(prediction['scores'])
#     return prediction['labels'][max_index]

In [16]:
from  tqdm import tqdm
actual_cate = []
predicted_cate = []

# Filter once to avoid the indexing bug
fiction_subset = books[books["broad_category"] == "Fiction"].reset_index(drop=True)

for i in tqdm(range(0, 300)):
    sequence = fiction_subset["tagged_description"][i]
    
    pred = generate_predictions(sequence, fiction_categories)
    
    predicted_cate.append(pred)
    actual_cate.append("Fiction")

100%|██████████| 300/300 [04:28<00:00,  1.12it/s]

In [ ]:
# Filter once to avoid the indexing bug
fiction_subset = books[books["broad_category"] == "NonFiction"].reset_index(drop=True)

for i in tqdm(range(0, 300)):
    sequence = fiction_subset["tagged_description"][i]
    
    pred = generate_predictions(sequence, fiction_categories)
    
    predicted_cate.append(pred)
    actual_cate.append("NonFiction")

100%|██████████| 300/300 [04:44<00:00,  1.05it/s]

In [ ]:
predictions_df=pd.DataFrame({"actual_category": actual_cate, "predicted_category": predicted_cate})

In [19]:
predictions_df

    actual_category predicted_category
0           Fiction            Fiction
1           Fiction            Fiction
2           Fiction            Fiction
3           Fiction            Fiction
4           Fiction            Fiction
..              ...                ...
595      NonFiction         NonFiction
596      NonFiction         NonFiction
597      NonFiction         NonFiction
598      NonFiction         NonFiction
599      NonFiction         NonFiction

[600 rows x 2 columns]

In [20]:
predictions_df["correct_prediction"]=np.where(predictions_df["actual_category"]==predictions_df["predicted_category"], 1, 0)

In [21]:
predictions_df["correct_prediction"].sum()/len(predictions_df)

np.float64(0.825)

In [22]:
isbns=[]
predicted_cats=[]

missing_cats=books.loc[books["broad_category"].isna(), ["isbn13", "tagged_description"]].reset_index(drop=True)

In [23]:
for i in tqdm(range(len(missing_cats))):
    sequence = missing_cats["tagged_description"][i]
    
    pred = generate_predictions(sequence, fiction_categories)
    
    predicted_cats.append(pred)
    isbns.append(missing_cats["isbn13"][i])

100%|██████████| 1454/1454 [21:26<00:00,  1.13it/s]

In [24]:
missing_predictions_df=pd.DataFrame({"isbn13": isbns, "predicted_category": predicted_cats})
missing_predictions_df

             isbn13 predicted_category
0     9780002261982            Fiction
1     9780006280897         NonFiction
2     9780006280934         NonFiction
3     9780006380832         NonFiction
4     9780006470229            Fiction
...             ...                ...
1449  9788125026600         NonFiction
1450  9788171565641            Fiction
1451  9788172235222            Fiction
1452  9788173031014         NonFiction
1453  9788179921623            Fiction

[1454 rows x 2 columns]

In [25]:
books=pd.merge(books, missing_predictions_df, on="isbn13", how="left")
books["books_category"]=np.where(books["broad_category"].isna(), books["predicted_category"], books["broad_category"])
books=books.drop(columns=["predicted_category"])

In [26]:
books.to_csv("books_with_categories.csv", index=False)